apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multi-ride-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: / # Optional: check if your backend expects /api or just /
spec:
  tls:
    - hosts:
        - maps.kaayaka.in
      secretName: maps-api-tls
  rules:
    - host: maps.kaayaka.in
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: svc-be-multi-ride
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-fe-multi-ride
                port:
                  number: 80
