apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: msite-ingress
  namespace: m-site
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - kaayaka.in
      secretName: mweb-tls
  rules:
    - host: "kaayaka.in"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mweb-service
                port:
                  number: 80
    - host: "www.kaayaka.in"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mweb-service
                port:
                  number: 80
